#!/bin/env bash

set -eu

EDITOR="nvim"
JOURNAL_PATH="$HOME/stuff/journal"

arg_day=""
day=$(date -I)
day_file="$JOURNAL_PATH/$(date +"%Y")/$day"
day_file_bak="/tmp/$day.bak"
template_path="$JOURNAL_PATH/template"

help() {
	echo "52 - document your year

Usage:
    52                       (open today's file in nvim)
    52 <option>              (see below)
    52 <activity> <args>     (add activity to today's file)

Options:
    -d, --delete             delete a key from today's file

    -e [YYYY-MM-DD], --edit  open date's file in an editor or today
                               or today's if no [DATE] supplied
    -c [YYYY-MM-DD], --cat   print [DATE]'s file
                               or today's if no [DATE] supplied
                               or write the template to the respective file
                               if it was empty before

    -t, --template           edit the template
    -u, --undo               return to the previous state before writing"
	exit 1
}

if [ $# -eq 0 ]; then
	$EDITOR "$day_file"
	exit
fi

touch $day_file

case $1 in
	"--delete"|"-d")
		if [ $# -eq 1 ]; then
			echo "Usage: 52 --delete <key>"
			exit 1
		fi

		shift 1
		for arg in "$@"; do
			escaped_arg=$(printf '%s\n' "$1" | sed 's/[][\\.^$*]/\\&/g')

			if ! grep -q "$escaped_arg" $day_file; then
				echo "Not found: $escaped_arg"
				exit 1
			fi
			sed -i "/$escaped_arg/d" $day_file
			echo "Deleted $escaped_arg"
		done

		exit
		;;
	"--edit"|"-e")
		if [ $# -ge 2 ]; then
			arg_day="$JOURNAL_PATH/${2:0:4}/$2"
		else
			arg_day=$day_file
		fi

		$EDITOR "$arg_day"
		exit
		;;
	"--template"|"-t")
		$EDITOR "$template_path"
		exit
		;;
	"--cat"|"-c")
		if [ $# -ge 2 ]; then
			arg_day="$JOURNAL_PATH/${2:0:4}/$2"
		else
			arg_day=$day_file
		fi

		if [ ! -s $arg_day ]; then
			cat $template_path > $arg_day
		fi
		cat $arg_day
		exit
		;;
	"--undo"|"-u")
		cat $day_file_bak > $day_file
		echo "Undid last change to '$day_file'"
		exit
		;;
	"-"*)
		help
		;;
esac

if grep -q "^$1\b" $day_file; then
	cat $day_file > $day_file_bak
	escaped_1=$(printf '%s\n' "$1" | sed 's/[][\\.^$*]/\\&/g')
	sed -i "/^$escaped_1/c\\$*" $day_file
	exit
fi

printf "$1 is a new activity. Do you want to add it? [Y/n]: "
read response
case $response in
	""|"Y"|"y")
		cat $day_file > $day_file_bak
		echo "$@" >> $day_file
		;;
	"N"|"n")
		exit
		;;
	*)
		echo "Invalid response!"
		exit 1
		;;
esac
